package ai.drfx.scalperpro.code

import ai.drfx.scalperpro.strategy.DirectionPermission
import ai.drfx.scalperpro.strategy.StrategySpecification

object PineStudioEngine {
    fun generate(
        specification: StrategySpecification
    ): CodeArtifact {
        val entryExpression = specification.entryConditions
            .joinToString(" and ") { "(" + it.expression + ")" }
            .ifBlank { "false" }

        val longAllowed = specification.directionPermission != DirectionPermission.SHORT_ONLY
        val shortAllowed = specification.directionPermission != DirectionPermission.LONG_ONLY

        val source = buildString {
            appendLine("//@version=6")
            appendLine("strategy(\"" + escape(specification.name) + "\", overlay=true, pyramiding=" + specification.pyramiding + ")")
            appendLine("// Generated by Scalper Pro from Strategy Specification.")
            appendLine("// Verification: generated + static analysis only; TradingView compile not performed.")
            appendLine("// Symbol: " + specification.symbol)
            appendLine("// Primary timeframe: " + specification.primaryTimeframe)
            appendLine()
            appendLine("entryCondition = " + entryExpression)
            if (longAllowed) {
                appendLine("if entryCondition")
                appendLine("    strategy.entry(\"L\", strategy.long)")
            }
            if (shortAllowed) {
                appendLine("// Short permission enabled. Add an explicit short-condition expression before production use.")
            }
            appendLine()
            appendLine("// Stop method: " + specification.stop.method.name)
            appendLine("// Take-profit method: " + specification.takeProfit.method.name)
            appendLine("// Risk % per trade: " + specification.risk.riskPercentPerTrade)
            appendLine("// Session: " + (specification.session?.allowedWindows?.joinToString(", ") ?: "unrestricted"))
        }

        val findings = PineStaticAnalyzer.analyze(source)
        return CodeArtifact(
            language = CodeLanguage.PINE,
            source = source,
            verificationStatus = VerificationStatus.STATIC_ANALYZED,
            findings = findings
        )
    }

    private fun escape(value: String): String =
        value.replace("\\", "\\\\").replace("\"", "\\\"")
}

object PineStaticAnalyzer {
    fun analyze(source: String): List<CodeFinding> {
        val findings = mutableListOf<CodeFinding>()
        val lowered = source.lowercase()

        if ("barmerge.lookahead_on" in lowered) {
            findings += CodeFinding(
                severity = "ERROR",
                code = "PINE_LOOKAHEAD_ON",
                message = "barmerge.lookahead_on can introduce future leakage."
            )
        }

        if ("request.security" in lowered && "lookahead" !in lowered) {
            findings += CodeFinding(
                severity = "WARNING",
                code = "PINE_SECURITY_REVIEW",
                message = "request.security usage should be reviewed for timeframe alignment and lookahead behavior."
            )
        }

        if ("strategy.entry" !in lowered && "indicator(" !in lowered) {
            findings += CodeFinding(
                severity = "INFO",
                code = "PINE_NO_ENTRY",
                message = "No strategy.entry call was detected."
            )
        }

        if ("barstate.isconfirmed" !in lowered) {
            findings += CodeFinding(
                severity = "INFO",
                code = "PINE_CONFIRMATION_REVIEW",
                message = "Review whether bar confirmation is required to avoid intrabar repaint behavior."
            )
        }

        return findings
    }
}
