package ai.drfx.scalperpro.code

import ai.drfx.scalperpro.strategy.DirectionPermission
import ai.drfx.scalperpro.strategy.StopMethod
import ai.drfx.scalperpro.strategy.StrategyCondition
import ai.drfx.scalperpro.strategy.StrategySpecification
import ai.drfx.scalperpro.strategy.TakeProfitMethod

object PineStudioEngine {
    fun generate(
        specification: StrategySpecification
    ): CodeArtifact {
        val longAllowed =
            specification.directionPermission !=
                DirectionPermission.SHORT_ONLY
        val shortAllowed =
            specification.directionPermission !=
                DirectionPermission.LONG_ONLY

        val longExpression = conjunction(
            specification.entryConditions +
                specification.filters
        )
        val shortExpression = conjunction(
            specification.shortEntryConditions +
                specification.filters
        )

        val findings = mutableListOf<CodeFinding>()
        val stopDistance = stopDistanceExpression(
            specification,
            findings
        )
        val targetDistance = targetDistanceExpression(
            specification,
            stopDistance,
            findings
        )

        if (
            shortAllowed &&
            specification.shortEntryConditions.isEmpty()
        ) {
            findings += CodeFinding(
                severity = "WARNING",
                code = "STRATEGY_SHORT_RULES_MISSING",
                message = "Short trading is allowed but no explicit short-entry conditions exist, so generated Pine will not open short positions."
            )
        }

        if (specification.newsFilter.enabled) {
            findings += CodeFinding(
                severity = "INFO",
                code = "STRATEGY_NEWS_FILTER_EXTERNAL",
                message = "The Strategy Specification requests a news filter. Pine cannot consume Scalper Pro's economic-calendar feed directly, so this filter remains external to the generated TradingView strategy."
            )
        }

        val source = buildString {
            appendLine("//@version=6")
            appendLine(
                "strategy(" +
                    "\"" + escape(specification.name) + "\"" +
                    ", overlay=true" +
                    ", pyramiding=" + specification.pyramiding +
                    ", calc_on_every_tick=false" +
                    ", process_orders_on_close=" +
                    specification.execution.processOrdersOnClose +
                    ", commission_type=strategy.commission.percent" +
                    ", commission_value=" +
                    number(specification.execution.commissionPercent) +
                    ", slippage=" +
                    specification.execution.slippageTicks +
                    ")"
            )
            appendLine(
                "// Generated by Scalper Pro from Strategy Specification."
            )
            appendLine(
                "// Verification: generated + static analysis only; TradingView compile not performed."
            )
            appendLine(
                "// Educational workflow: validate in TradingView before relying on results."
            )
            appendLine("// Symbol intent: " + specification.symbol)
            appendLine(
                "// Primary timeframe intent: " +
                    specification.primaryTimeframe
            )
            appendLine()

            appendLine(
                "riskPercent = input.float(" +
                    number(specification.risk.riskPercentPerTrade) +
                    ", \"Planned risk %\", minval=0.1, maxval=10.0, step=0.1, group=\"Risk\", tooltip=\"Planning metadata. TradingView order quantity still depends on the strategy Properties/order sizing configuration.\")"
            )
            appendLine(
                "cooldownBars = input.int(" +
                    specification.cooldownBars +
                    ", \"Cooldown bars\", minval=0, group=\"Execution\")"
            )
            appendLine(
                "var int lastEntryBar = na"
            )
            appendLine(
                "cooldownOk = na(lastEntryBar) or bar_index - lastEntryBar > cooldownBars"
            )
            appendLine()

            appendSessionFilter(specification)

            if (stopDistance != null) {
                if (
                    specification.stop.method ==
                    StopMethod.ATR_MULTIPLE
                ) {
                    appendLine(
                        "atrLength = input.int(14, \"ATR length\", minval=1, group=\"Stops & Targets\")"
                    )
                    appendLine(
                        "atrValue = ta.atr(atrLength)"
                    )
                }
                appendLine(
                    "stopDistance = " + stopDistance
                )
            }

            if (targetDistance != null) {
                appendLine(
                    "targetDistance = " + targetDistance
                )
            }

            if (
                stopDistance != null ||
                targetDistance != null
            ) {
                appendLine()
            }

            appendLine(
                "longSignal = " +
                    if (longAllowed) {
                        longExpression
                    } else {
                        "false"
                    }
            )
            appendLine(
                "shortSignal = " +
                    if (
                        shortAllowed &&
                        specification.shortEntryConditions
                            .isNotEmpty()
                    ) {
                        shortExpression
                    } else {
                        "false"
                    }
            )
            appendLine(
                "canEnter = barstate.isconfirmed and inSession and cooldownOk and strategy.position_size == 0"
            )
            appendLine()

            if (longAllowed) {
                appendLine(
                    "if canEnter and longSignal"
                )
                appendLine(
                    "    strategy.entry(\"L\", strategy.long)"
                )
                appendLine(
                    "    lastEntryBar := bar_index"
                )
            }

            if (
                shortAllowed &&
                specification.shortEntryConditions.isNotEmpty()
            ) {
                appendLine(
                    if (longAllowed) {
                        "else if canEnter and shortSignal"
                    } else {
                        "if canEnter and shortSignal"
                    }
                )
                appendLine(
                    "    strategy.entry(\"S\", strategy.short)"
                )
                appendLine(
                    "    lastEntryBar := bar_index"
                )
            }

            appendExitOrders(
                stopDistance = stopDistance,
                targetDistance = targetDistance
            )

            if (specification.exitConditions.isNotEmpty()) {
                appendLine()
                appendLine(
                    "ruleExit = " +
                        disjunction(
                            specification.exitConditions
                        )
                )
                appendLine(
                    "if barstate.isconfirmed and ruleExit and strategy.position_size != 0"
                )
                appendLine(
                    "    strategy.close_all(comment=\"Rule exit\")"
                )
            }

            appendLine()
            appendLine(
                "// Direction permission: " +
                    specification.directionPermission.name
            )
            appendLine(
                "// Stop method: " +
                    specification.stop.method.name
            )
            appendLine(
                "// Take-profit method: " +
                    specification.takeProfit.method.name
            )
            appendLine(
                "// Session: " +
                    (
                        specification.session
                            ?.allowedWindows
                            ?.joinToString(", ")
                            ?: "unrestricted"
                    )
            )

            if (specification.newsFilter.enabled) {
                appendLine(
                    "// News filter is enforced by Scalper Pro context, not by this standalone Pine script."
                )
            }
        }

        findings += PineStaticAnalyzer.analyze(source)

        return CodeArtifact(
            language = CodeLanguage.PINE,
            source = source,
            verificationStatus =
                VerificationStatus.STATIC_ANALYZED,
            findings = findings.distinctBy {
                it.code
            }
        )
    }

    private fun StringBuilder.appendSessionFilter(
        specification: StrategySpecification
    ) {
        val session = specification.session

        if (
            session == null ||
            session.allowedWindows.isEmpty()
        ) {
            appendLine("inSession = true")
            return
        }

        session.allowedWindows.forEachIndexed {
                index,
                window ->
            appendLine(
                "session" + (index + 1) +
                    " = not na(time(timeframe.period, \"" +
                    escape(window) +
                    "\", \"" +
                    escape(session.timezone) +
                    "\"))"
            )
        }

        appendLine(
            "inSession = " +
                session.allowedWindows.indices
                    .joinToString(" or ") {
                        "session" + (it + 1)
                    }
        )
    }

    private fun StringBuilder.appendExitOrders(
        stopDistance: String?,
        targetDistance: String?
    ) {
        if (
            stopDistance == null &&
            targetDistance == null
        ) {
            return
        }

        appendLine()
        appendLine("if strategy.position_size > 0")
        append(
            "    strategy.exit(\"L-X\", from_entry=\"L\""
        )
        if (stopDistance != null) {
            append(
                ", stop=strategy.position_avg_price - stopDistance"
            )
        }
        if (targetDistance != null) {
            append(
                ", limit=strategy.position_avg_price + targetDistance"
            )
        }
        appendLine(")")

        appendLine("if strategy.position_size < 0")
        append(
            "    strategy.exit(\"S-X\", from_entry=\"S\""
        )
        if (stopDistance != null) {
            append(
                ", stop=strategy.position_avg_price + stopDistance"
            )
        }
        if (targetDistance != null) {
            append(
                ", limit=strategy.position_avg_price - targetDistance"
            )
        }
        appendLine(")")
    }

    private fun stopDistanceExpression(
        specification: StrategySpecification,
        findings: MutableList<CodeFinding>
    ): String? =
        when (specification.stop.method) {
            StopMethod.FIXED_PRICE_DISTANCE ->
                specification.stop.value?.let {
                    number(it)
                }

            StopMethod.ATR_MULTIPLE ->
                specification.stop.value?.let {
                    "atrValue * " + number(it)
                }

            StopMethod.STRUCTURE -> {
                findings += CodeFinding(
                    severity = "WARNING",
                    code = "STRATEGY_STRUCTURE_STOP_NOT_COMPILED",
                    message = "Structure-based stop logic requires an explicit deterministic expression before Pine generation can place the stop."
                )
                null
            }

            StopMethod.CUSTOM -> {
                val expression =
                    specification.stop.expression
                        ?.trim()
                        .orEmpty()

                if (expression.isBlank()) {
                    findings += CodeFinding(
                        severity = "ERROR",
                        code = "STRATEGY_CUSTOM_STOP_MISSING",
                        message = "Custom stop method has no expression."
                    )
                    null
                } else {
                    expression
                }
            }
        }

    private fun targetDistanceExpression(
        specification: StrategySpecification,
        stopDistance: String?,
        findings: MutableList<CodeFinding>
    ): String? =
        when (specification.takeProfit.method) {
            TakeProfitMethod.FIXED_R_MULTIPLE -> {
                val multiple =
                    specification.takeProfit.value

                if (
                    stopDistance == null ||
                    multiple == null
                ) {
                    findings += CodeFinding(
                        severity = "WARNING",
                        code = "STRATEGY_R_TARGET_NEEDS_STOP",
                        message = "Fixed-R target requires a deterministic stop distance."
                    )
                    null
                } else {
                    "stopDistance * " +
                        number(multiple)
                }
            }

            TakeProfitMethod.FIXED_PRICE_DISTANCE ->
                specification.takeProfit.value
                    ?.let { number(it) }

            TakeProfitMethod.STRUCTURE -> {
                findings += CodeFinding(
                    severity = "WARNING",
                    code = "STRATEGY_STRUCTURE_TARGET_NOT_COMPILED",
                    message = "Structure-based target logic requires an explicit deterministic expression before Pine generation can place the target."
                )
                null
            }

            TakeProfitMethod.TRAILING -> {
                findings += CodeFinding(
                    severity = "INFO",
                    code = "STRATEGY_TRAILING_NEEDS_ACTIVATION",
                    message = "Trailing exits require an explicit activation and offset contract; Scalper Pro will not invent one."
                )
                null
            }

            TakeProfitMethod.CUSTOM -> {
                val expression =
                    specification.takeProfit.expression
                        ?.trim()
                        .orEmpty()

                if (expression.isBlank()) {
                    findings += CodeFinding(
                        severity = "ERROR",
                        code = "STRATEGY_CUSTOM_TARGET_MISSING",
                        message = "Custom take-profit method has no expression."
                    )
                    null
                } else {
                    expression
                }
            }
        }

    private fun conjunction(
        conditions: List<StrategyCondition>
    ): String =
        conditions
            .joinToString(" and ") {
                "(" + it.expression + ")"
            }
            .ifBlank { "false" }

    private fun disjunction(
        conditions: List<StrategyCondition>
    ): String =
        conditions
            .joinToString(" or ") {
                "(" + it.expression + ")"
            }
            .ifBlank { "false" }

    private fun number(value: Double): String =
        if (value % 1.0 == 0.0) {
            value.toLong().toString() + ".0"
        } else {
            value.toString()
        }

    private fun escape(value: String): String =
        value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
}

object PineStaticAnalyzer {
    fun analyze(source: String): List<CodeFinding> {
        val findings = mutableListOf<CodeFinding>()
        val lowered = source.lowercase()
        val compact = lowered.replace(Regex("\\s+"), " ")

        if (!lowered.contains("//@version=6")) {
            findings += CodeFinding(
                severity = "INFO",
                code = "PINE_VERSION_REVIEW",
                message = "Scalper Pro targets Pine Script v6 for new code; review compatibility if this script uses another version."
            )
        }

        if ("barmerge.lookahead_on" in lowered) {
            findings += CodeFinding(
                severity = "ERROR",
                code = "PINE_LOOKAHEAD_ON",
                message = "barmerge.lookahead_on can introduce future leakage into historical signals."
            )
        }

        if ("request.security" in lowered) {
            if ("lookahead=barmerge.lookahead_off" !in compact &&
                "lookahead = barmerge.lookahead_off" !in compact
            ) {
                findings += CodeFinding(
                    severity = "INFO",
                    code = "PINE_SECURITY_LOOKAHEAD_EXPLICIT",
                    message = "request.security is present. Consider making lookahead_off explicit so higher-timeframe intent is obvious during review."
                )
            }

            if (!Regex("""request\.security[\s\S]{0,260}\[1]""")
                    .containsMatchIn(lowered)
            ) {
                findings += CodeFinding(
                    severity = "WARNING",
                    code = "PINE_HTF_CONFIRMATION_REVIEW",
                    message = "Higher-timeframe request detected without an obvious [1] confirmed-bar offset nearby. Verify that live HTF values cannot repaint the intended signal."
                )
            }
        }

        val hasAlerts =
            "alert(" in lowered ||
                "alertcondition(" in lowered

        val hasBarCloseAlertContract =
            "barstate.isconfirmed" in lowered ||
                "alert.freq_once_per_bar_close" in lowered

        if (hasAlerts && !hasBarCloseAlertContract) {
            findings += CodeFinding(
                severity = "WARNING",
                code = "PINE_ALERT_TIMING_REVIEW",
                message = "Alerts are present without an obvious confirmed-bar or once-per-bar-close contract. Verify whether intrabar alert changes are intentional."
            )
        }

        val isStrategy = "strategy(" in lowered

        if (isStrategy && "calc_on_every_tick=true" in compact) {
            findings += CodeFinding(
                severity = "WARNING",
                code = "PINE_INTRABAR_STRATEGY_REVIEW",
                message = "calc_on_every_tick=true can make realtime strategy behavior differ from historical bar-based results."
            )
        }

        if (isStrategy) {
            if ("commission_type" !in lowered && "commission_value" !in lowered) {
                findings += CodeFinding(
                    severity = "INFO",
                    code = "PINE_COMMISSION_REVIEW",
                    message = "No explicit strategy commission model was detected. Add realistic costs before interpreting backtest performance."
                )
            }

            if ("slippage" !in lowered) {
                findings += CodeFinding(
                    severity = "INFO",
                    code = "PINE_SLIPPAGE_REVIEW",
                    message = "No explicit strategy slippage assumption was detected. Short-timeframe systems are especially sensitive to execution costs."
                )
            }
        }

        if ("strategy.entry" !in lowered && "indicator(" !in lowered) {
            findings += CodeFinding(
                severity = "INFO",
                code = "PINE_NO_ENTRY",
                message = "No strategy.entry call or indicator declaration was detected."
            )
        }

        val persistentStateCount =
            Regex("""(?m)^\s*var\s+""")
                .findAll(lowered)
                .count()

        if (persistentStateCount >= 3) {
            findings += CodeFinding(
                severity = "INFO",
                code = "PINE_STATE_HYGIENE_REVIEW",
                message = "The script has multiple persistent var states. Review every exit, invalidation and replacement path to ensure state is reset consistently."
            )
        }

        val loopCount =
            Regex("""(?m)^\s*for\s+""")
                .findAll(lowered)
                .count()

        if (loopCount >= 5) {
            findings += CodeFinding(
                severity = "WARNING",
                code = "PINE_RUNTIME_COST_REVIEW",
                message = "Several loops were detected. Review per-bar runtime, history depth and nested work to avoid execution limits."
            )
        }

        val inputCount =
            Regex("""input\.(int|float|bool|string|color|timeframe|session)\(""")
                .findAll(lowered)
                .count()

        if (inputCount >= 4 && "tooltip=" !in compact) {
            findings += CodeFinding(
                severity = "INFO",
                code = "PINE_INPUT_TOOLTIP_REVIEW",
                message = "Several user inputs are present but no tooltips were detected. Beginner-facing scripts benefit from concise parameter guidance."
            )
        }

        if (inputCount >= 4 && "group=" !in compact) {
            findings += CodeFinding(
                severity = "INFO",
                code = "PINE_INPUT_GROUP_REVIEW",
                message = "Several user inputs are present but no input groups were detected. Group related settings for a cleaner TradingView experience."
            )
        }

        if (!hasBarCloseAlertContract && !hasAlerts) {
            findings += CodeFinding(
                severity = "INFO",
                code = "PINE_CONFIRMATION_REVIEW",
                message = "Review whether confirmed-bar logic is required for the script's signals and visuals."
            )
        }

        return findings.distinctBy { it.code }
    }
}
