package ai.drfx.scalperpro.code

import ai.drfx.scalperpro.indicator.IndicatorSpecification
import ai.drfx.scalperpro.indicator.IndicatorSpecificationValidator
import ai.drfx.scalperpro.indicator.RepaintPolicy

object PineIndicatorGenerator {
    fun generate(
        specification: IndicatorSpecification
    ): CodeArtifact {
        val validation = IndicatorSpecificationValidator.validate(specification)

        if (!validation.valid) {
            return CodeArtifact(
                language = CodeLanguage.PINE,
                source = "",
                verificationStatus = VerificationStatus.GENERATED_UNVERIFIED,
                findings = validation.errors.map { error ->
                    CodeFinding(
                        severity = "ERROR",
                        code = "INDICATOR_SPEC_INVALID",
                        message = error
                    )
                }
            )
        }

        val source = buildString {
            appendLine("//@version=6")
            appendLine(
                "indicator(\"" + escape(specification.name) +
                    "\", shorttitle=\"" + escape(specification.shortTitle) +
                    "\", overlay=" + specification.overlay + ")"
            )
            appendLine("// Generated by Scalper Pro from an Indicator Specification.")
            appendLine("// Educational tool: review and test before using on live markets.")
            appendLine()

            specification.inputs.forEach { input ->
                val variable = inputVariable(input.id)
                val group = input.group?.let { ", group=\\\"" + escape(it) + "\\\"" }.orEmpty()
                val tooltip = input.tooltip?.let { ", tooltip=\\\"" + escape(it) + "\\\"" }.orEmpty()
                val range = buildString {
                    input.minValue?.let { append(", minval=$it") }
                    input.maxValue?.let { append(", maxval=$it") }
                }

                val declaration = when (input.type.lowercase()) {
                    "float" ->
                        "$variable = input.float(${input.defaultValue}, \\\"${escape(input.title)}\\\"$range$group$tooltip)"
                    "bool" ->
                        "$variable = input.bool(${input.defaultValue}, \\\"${escape(input.title)}\\\"$group$tooltip)"
                    "string" ->
                        "$variable = input.string(\\\"${escape(input.defaultValue)}\\\", \\\"${escape(input.title)}\\\"$group$tooltip)"
                    else ->
                        "$variable = input.int(${input.defaultValue}, \\\"${escape(input.title)}\\\"$range$group$tooltip)"
                }
                appendLine(declaration)
            }

            if (specification.inputs.isNotEmpty()) appendLine()

            specification.calculations.forEach { calculation ->
                appendLine(calculation.variable + " = " + calculation.expression)
            }

            if (specification.calculations.isNotEmpty()) appendLine()

            specification.plots.forEach { plot ->
                appendLine(
                    "plot(" + plot.expression +
                        ", title=\"" + escape(plot.title) +
                        "\", color=" + plot.color +
                        ", linewidth=" + plot.width + ")"
                )
            }

            if (specification.alerts.isNotEmpty()) {
                appendLine()
                specification.alerts.forEach { alert ->
                    appendLine(
                        "alertcondition(" + alert.conditionExpression +
                            ", title=\"" + escape(alert.title) +
                            "\", message=\"" + escape(alert.messageTemplate) + "\")"
                    )
                }
            }

            appendLine()
            when (specification.repaintPolicy) {
                RepaintPolicy.CONFIRMED_BARS_ONLY ->
                    appendLine("// Repaint policy: signals should use confirmed bars.")
                RepaintPolicy.INTRABAR_ALLOWED ->
                    appendLine("// Repaint policy: intrabar updates are intentionally allowed.")
                RepaintPolicy.VISUAL_ONLY ->
                    appendLine("// Repaint policy: visual-only tool; do not treat transient values as confirmed signals.")
            }
            appendLine("// Designed timeframes: " + specification.designedTimeframes.joinToString(", "))
        }

        val findings = PineStaticAnalyzer.analyze(source)

        return CodeArtifact(
            language = CodeLanguage.PINE,
            source = source,
            verificationStatus = VerificationStatus.STATIC_ANALYZED,
            findings = findings
        )
    }

    private fun inputVariable(id: String): String =
        when (id) {
            "fast" -> "fastLen"
            "slow" -> "slowLen"
            "rsi" -> "rsiLen"
            else -> id
                .replace(Regex("[^A-Za-z0-9_]"), "_")
                .let { value ->
                    if (value.firstOrNull()?.isDigit() == true) {
                        "input_$value"
                    } else {
                        value.ifBlank { "inputValue" }
                    }
                }
        }

    private fun escape(value: String): String =
        value.replace("\\\\", "\\\\\\\\").replace("\\\"", "\\\\\\\"")
}
